# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb.arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_app_ecswo-Front-1M69OSRSV4E9Z_65bb782bf8b1d07b:
resource "aws_lb" "arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_app_ecswo-Front-1M69OSRSV4E9Z_65bb782bf8b1d07b" {
  desync_mitigation_mode                      = "defensive"
  drop_invalid_header_fields                  = false
  enable_cross_zone_load_balancing            = true
  enable_deletion_protection                  = false
  enable_http2                                = true
  enable_tls_version_and_cipher_suite_headers = false
  enable_waf_fail_open                        = false
  enable_xff_client_port                      = false
  idle_timeout                                = 60
  internal                                    = false
  ip_address_type                             = "ipv4"
  load_balancer_type                          = "application"
  name                                        = "ecswo-Front-1M69OSRSV4E9Z"
  preserve_host_header                        = false
  security_groups = [
    aws_security_group.sg-0a8c1a070641f7c30.id,
  ]
  subnets = [
    aws_subnet.subnet-07b8d4e34ea1baed5.id,
    aws_subnet.subnet-0b577247c767ac4c5.id,
    aws_subnet.subnet-0cb7f045d1e65a317.id,
  ]
  tags                       = {}
  tags_all                   = {}
  xff_header_processing_mode = "append"

  access_logs {
    bucket  = ""
    enabled = false
  }

}
