# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb.arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_app_ecswo-Front-1M69OSRSV4E9Z_65bb782bf8b1d07b:
resource "aws_lb" "arn_aws_elasticloadbalancing_eu-west-2_566972129213_loadbalancer_app_ecswo-Front-1M69OSRSV4E9Z_65bb782bf8b1d07b" {
  desync_mitigation_mode                      = "defensive"
  drop_invalid_header_fields                  = false
  enable_cross_zone_load_balancing            = true
  enable_deletion_protection                  = false
  enable_http2                                = true
  enable_tls_version_and_cipher_suite_headers = false
  enable_waf_fail_open                        = false
  enable_xff_client_port                      = false
  idle_timeout                                = 60
  internal                                    = false
  ip_address_type                             = "ipv4"
  load_balancer_type                          = "application"
  name                                        = "ecsworkshop-front"
  preserve_host_header                        = false
  security_groups = [
    data.aws_ssm_parameter.lbautosg.value,
  ]
  subnets = [
    data.aws_ssm_parameter.publicsubnet1.value,
    data.aws_ssm_parameter.publicsubnet2.value,
    data.aws_ssm_parameter.publicsubnet3.value,
  ]
  tags                       = {}
  tags_all                   = {}
  xff_header_processing_mode = "append"

  access_logs {
    bucket  = ""
    enabled = false
  }

}
