# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_service.container-demo__ecsdemo-frontend:
resource "aws_ecs_service" "container-demo__ecsdemo-frontend" {
  cluster                            = data.aws_ssm_parameter.cluster.arn
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 50
  desired_count                      = 1
  enable_ecs_managed_tags            = false
  enable_execute_command             = false
  health_check_grace_period_seconds  = 60
  #iam_role                           = "/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"
  launch_type                        = "FARGATE"
  name                               = "ecsdemo-frontend"
  platform_version                   = "LATEST"
  scheduling_strategy                = "REPLICA"
  tags                               = {}
  tags_all                           = {}
  task_definition = aws_ecs_task_definition.ecsworkshopfrontendFrontendFargateLBServiceTaskDefDA36BB44_1.arn

  #task_definition                    = "ecsworkshopfrontendFrontendFargateLBServiceTaskDefDA36BB44:1"
  triggers                           = {}

  deployment_circuit_breaker {
    enable   = false
    rollback = false
  }

  deployment_controller {
    type = "ECS"
  }

  load_balancer {
    container_name   = "web"
    container_port   = 3000
    target_group_arn = aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-2_566972129213_targetgroup_ecswor-Front-VWZBXC2NOHYZ_980ebe2e449dec23.arn
    #target_group_arn = format("arn:aws:elasticloadbalancing:%s:%s:targetgroup/ecswor-Front-VWZBXC2NOHYZ/980ebe2e449dec23", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
  }

  network_configuration {
    assign_public_ip = false
    security_groups = [
      data.aws_ssm_parameter.lbsg.value,
    ]
    subnets = [
      data.aws_ssm_parameter.privatesubnet1.value,
      data.aws_ssm_parameter.privatesubnet2.value,
      data.aws_ssm_parameter.privatesubnet3.value,
    ]
  }

  service_registries {
    container_port = 0
    port           = 0
    registry_arn   = "arn:aws:servicediscovery:eu-west-2:566972129213:service/srv-drywcrjoa2ul3ybn"
  }
}
