# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.r-ecsworkshop-frontend-FrontendFargateLBServiceTaskD-WUGLT64IDJAJ__FrontendFargateLBServiceTaskDefTaskRoleDefaultPolicy64DA05F5:
resource "aws_iam_role_policy" "r-ecsworkshop-frontend-FrontendFargateLBServiceTaskD-WUGLT64IDJAJ__FrontendFargateLBServiceTaskDefTaskRoleDefaultPolicy64DA05F5" {
  name = "FrontendFargateLBServiceTaskDefTaskRoleDefaultPolicy64DA05F5"
  policy = jsonencode(
    {
      Statement = [
        {
          Action   = "ec2:DescribeSubnets"
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.r-ecsworkshop-frontend-FrontendFargateLBServiceTaskD-WUGLT64IDJAJ.id
}
