# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_task_definition.ecsworkshopfrontendFrontendFargateLBServiceTaskDefDA36BB44_1:
resource "aws_ecs_task_definition" "ecsworkshopfrontendFrontendFargateLBServiceTaskDefDA36BB44_1" {
  container_definitions = jsonencode(
    [
      {
        command               = []
        cpu                   = 0
        dnsSearchDomains      = []
        dnsServers            = []
        dockerLabels          = {}
        dockerSecurityOptions = []
        entryPoint            = []
        environment = [
          {
            name  = "CRYSTAL_URL"
            value = "http://ecsdemo-crystal.service.local:3000/crystal"
          },
          {
            name  = "NODEJS_URL"
            value = "http://ecsdemo-nodejs.service.local:3000"
          },
          {
            name  = "REGION"
            value = "eu-west-2"
          },
        ]
        environmentFiles = []
        essential        = true
        extraHosts       = []
        image            = "public.ecr.aws/aws-containers/ecsdemo-frontend"
        links            = []
        logConfiguration = {
          logDriver = "awslogs"
          options = {
            awslogs-group         = aws_cloudwatch_log_group.ecsworkshop-frontend-FrontendFargateLBServiceTaskDefwebLogGroup3132F919-8PPYoyUGSUb3.name
            awslogs-region        = "eu-west-2"
            awslogs-stream-prefix = "FrontendFargateLBService"
          }
          secretOptions = []
        }
        mountPoints = []
        name        = "web"
        portMappings = [
          {
            containerPort = 3000
            hostPort      = 3000
            protocol      = "tcp"
          },
        ]
        secrets        = []
        systemControls = []
        ulimits        = []
        volumesFrom    = []
      },
    ]
  )
  cpu                = "256"
  execution_role_arn = aws_iam_role.r-ecsworkshop-frontend-FrontendFargateLBServiceTaskD-ODJC573ZBWF4.arn
  family             = "ecsworkshopfrontendFrontendFargateLBServiceTaskDefDA36BB44"
  memory             = "512"
  network_mode       = "awsvpc"
  requires_compatibilities = [
    "FARGATE",
  ]
  tags          = {}
  tags_all      = {}
  task_role_arn = aws_iam_role.r-ecsworkshop-frontend-FrontendFargateLBServiceTaskD-WUGLT64IDJAJ.arn
}
