# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.ecsworkshop-frontend-FrontendFargateLBServiceTaskDefwebLogGroup3132F919-8PPYoyUGSUb3:
resource "aws_cloudwatch_log_group" "ecsworkshop-frontend-FrontendFargateLBServiceTaskDefwebLogGroup3132F919-8PPYoyUGSUb3" {
  name              = "ecsworkshop-frontend-FrontendFargateLBServiceTaskDefwebLogGroup3132F919-8PPYoyUGSUb3"
  retention_in_days = 0
  tags              = {}
  tags_all          = {}
}
