# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.ecsworkshop-nodejs-ecsworkshopNodejsF670245F-jnKh4tbV32Iu:
resource "aws_cloudwatch_log_group" "ecsworkshop-nodejs-ecsworkshopNodejsF670245F-jnKh4tbV32Iu" {
  name              = "ecsworkshop-nodejs-ecsworkshopNodejsF670245F-jnKh4tbV32Iu"
  retention_in_days = 7
  tags              = {}
  tags_all          = {}
}
