# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_capacity_provider.EC2Spot1615553699:
resource "aws_ecs_capacity_provider" "EC2Spot1615553699" {
  name     = "EC2Spot1615553699"
  tags     = {}
  tags_all = {}

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "arn:aws:autoscaling:eu-west-2:566972129213:autoScalingGroup:d7270441-98db-45ee-93b9-d1e357923baa:autoScalingGroupName/ecsworkshop-base-ECSEC2SpotCapacity-1OSL534BX4AW8"
    managed_termination_protection = "DISABLED"

    managed_scaling {
      instance_warmup_period    = 300
      maximum_scaling_step_size = 10000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 80
    }
  }
}
