# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_capacity_provider.EC2Spot1615652546:
resource "aws_ecs_capacity_provider" "EC2Spot1615652546" {
  name     = "EC2Spot1615652546"
  tags     = {}
  tags_all = {}

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "arn:aws:autoscaling:eu-west-2:566972129213:autoScalingGroup:a60fd81d-bc3b-4449-8ca9-f4f000413e50:autoScalingGroupName/ecsworkshop-base-ECSEC2SpotCapacity-QU4KC0SMQJUF"
    managed_termination_protection = "DISABLED"

    managed_scaling {
      instance_warmup_period    = 300
      maximum_scaling_step_size = 10000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 80
    }
  }
}
