# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_capacity_provider.EC21615652539:
resource "aws_ecs_capacity_provider" "EC21615652539" {
  name     = "EC21615652539"
  tags     = {}
  tags_all = {}

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "arn:aws:autoscaling:eu-west-2:566972129213:autoScalingGroup:1d1d0a1e-4ddb-401d-b2fe-4f1d87eaf427:autoScalingGroupName/ecsworkshop-base-ECSClusterECSEC2CapacityASG0360B1DE-98NDMMC5HZ3M"
    managed_termination_protection = "DISABLED"

    managed_scaling {
      instance_warmup_period    = 300
      maximum_scaling_step_size = 10000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 80
    }
  }
}
