# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_capacity_provider.EC2Spot1615645666:
resource "aws_ecs_capacity_provider" "EC2Spot1615645666" {
  name     = "EC2Spot1615645666"
  tags     = {}
  tags_all = {}

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "arn:aws:autoscaling:eu-west-2:566972129213:autoScalingGroup:622f5186-23c3-4549-8464-137569c20e91:autoScalingGroupName/ecsworkshop-base-ECSEC2SpotCapacity-MDCXQ60GIH8P"
    managed_termination_protection = "DISABLED"

    managed_scaling {
      instance_warmup_period    = 300
      maximum_scaling_step_size = 10000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 80
    }
  }
}
