# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_capacity_provider.EC21615564563:
resource "aws_ecs_capacity_provider" "EC21615564563" {
  name     = "EC21615564563"
  tags     = {}
  tags_all = {}

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "arn:aws:autoscaling:eu-west-2:566972129213:autoScalingGroup:fa8f5bf8-4d51-4c1c-b50e-a2ad96e0c0ff:autoScalingGroupName/ecsworkshop-base-ECSClusterECSEC2CapacityASG0360B1DE-11VSPDVN2XS0P"
    managed_termination_protection = "DISABLED"

    managed_scaling {
      instance_warmup_period    = 300
      maximum_scaling_step_size = 10000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 80
    }
  }
}
