  ECSClusterECSEC2CapacityASG0360B1DE:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "5"
      MinSize: "0"
      LaunchConfigurationName:
        Ref: ECSClusterECSEC2CapacityLaunchConfigC81E218C
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: ecsworkshop-base/ECSCluster/ECSEC2Capacity
      VPCZoneIdentifier:
        - Ref: BaseVPCPrivateSubnet1SubnetF99B1DA5
        - Ref: BaseVPCPrivateSubnet2Subnet88334406
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
    Metadata:
      aws:cdk:path: ecsworkshop-base/ECSCluster/ECSEC2Capacity/ASG



    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT15M
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: true
