# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-061a3e11c868dec09__rtbassoc-09fee184bebb9c28b:
resource "aws_route_table_association" "subnet-061a3e11c868dec09__rtbassoc-09fee184bebb9c28b" {
  route_table_id = aws_route_table.rtb-0cec3c13f0ded7540.id
  subnet_id      = aws_subnet.subnet-061a3e11c868dec09.id
}
