# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eip.eipalloc-04cb97a0cfce3cd27:
resource "aws_eip" "eipalloc-04cb97a0cfce3cd27" {
  network_border_group = "eu-west-2"
  public_ipv4_pool     = "amazon"
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
  vpc = true
}
