# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0336ba9305f717ce8_ingress_1:
resource "aws_security_group_rule" "sg-0336ba9305f717ce8_ingress_1" {
  description              = "Load balancer to target"
  from_port                = 3000
  prefix_list_ids          = []
  protocol                 = "tcp"
  security_group_id        = aws_security_group.sg-0336ba9305f717ce8.id
  source_security_group_id = aws_security_group.sg-0a8c1a070641f7c30.id
  to_port                  = 3000
  type                     = "ingress"
}
