# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eip.eipalloc-05597bdae281532b1:
resource "aws_eip" "eipalloc-05597bdae281532b1" {
  network_border_group = "eu-west-2"
  public_ipv4_pool     = "amazon"
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet2"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet2"
  }
  vpc = true
}
