# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0336ba9305f717ce8:
resource "aws_security_group" "sg-0336ba9305f717ce8" {
  description = "ecsworkshop-frontend/FrontendFargateLBService/Service/SecurityGroup"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-0f8d08139ec381ee8.id
}
