# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-00632eb9de1e427f4:
resource "aws_nat_gateway" "nat-00632eb9de1e427f4" {
  allocation_id     = aws_eip.eipalloc-04cb97a0cfce3cd27.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-07b8d4e34ea1baed5.id
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet3"
  }
}
