# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-00207f50490cd7862:
resource "aws_nat_gateway" "nat-00207f50490cd7862" {
  allocation_id     = aws_eip.eipalloc-05597bdae281532b1.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-0b577247c767ac4c5.id
  tags = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet2"
  }
  tags_all = {
    "Name" = "ecsworkshop-base/BaseVPC/PublicSubnet2"
  }
}
