# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0b48672cbf7717766_ingress_2:
resource "aws_security_group_rule" "sg-0b48672cbf7717766_ingress_2" {
  description              = "from ecsworkshopfrontendFrontendFargateLBServiceSecurityGroupCB94C867:frontendtobackend"
  from_port                = 3000
  prefix_list_ids          = []
  protocol                 = "tcp"
  security_group_id        = aws_security_group.sg-0b48672cbf7717766.id
  source_security_group_id = aws_security_group.sg-0336ba9305f717ce8.id
  to_port                  = 3000
  type                     = "ingress"
}
