# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0c00f06ac09e279ac__rtbassoc-0a19cd0f3c2b5d293:
resource "aws_route_table_association" "subnet-0c00f06ac09e279ac__rtbassoc-0a19cd0f3c2b5d293" {
  route_table_id = aws_route_table.rtb-07cec655bec0ff518.id
  subnet_id      = aws_subnet.subnet-0c00f06ac09e279ac.id
}
