# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0b577247c767ac4c5__rtbassoc-021ae75097d29105b:
resource "aws_route_table_association" "subnet-0b577247c767ac4c5__rtbassoc-021ae75097d29105b" {
  route_table_id = aws_route_table.rtb-02617417e315c569b.id
  subnet_id      = aws_subnet.subnet-0b577247c767ac4c5.id
}
