# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-002db849c8babcf4b__rtbassoc-025546441bf366390:
resource "aws_route_table_association" "subnet-002db849c8babcf4b__rtbassoc-025546441bf366390" {
  route_table_id = aws_route_table.rtb-094f4eae659a141ac.id
  subnet_id      = aws_subnet.subnet-002db849c8babcf4b.id
}
