# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0a8c1a070641f7c30_ingress_1:
resource "aws_security_group_rule" "sg-0a8c1a070641f7c30_ingress_1" {
  cidr_blocks = [
    "0.0.0.0/0",
  ]
  description       = "Allow from anyone on port 80"
  from_port         = 80
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-0a8c1a070641f7c30.id
  to_port           = 80
  type              = "ingress"
}
