# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0b48672cbf7717766:
resource "aws_security_group" "sg-0b48672cbf7717766" {
  description = "Security group for frontend service to talk to backend services"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-0f8d08139ec381ee8.id
}
