# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0b48672cbf7717766_ingress_1:
resource "aws_security_group_rule" "sg-0b48672cbf7717766_ingress_1" {
  from_port         = 3000
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-0b48672cbf7717766.id
  self              = true
  to_port           = 3000
  type              = "ingress"
}
