# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-ecsworkshop-base-InstanceSSMCBFA3CF0-BKXGZVPPRO9K__AmazonEC2RoleforSSM:
resource "aws_iam_role_policy_attachment" "r-ecsworkshop-base-InstanceSSMCBFA3CF0-BKXGZVPPRO9K__AmazonEC2RoleforSSM" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
  role       = aws_iam_role.r-ecsworkshop-base-InstanceSSMCBFA3CF0-BKXGZVPPRO9K.id
}
