# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0cb7f045d1e65a317__rtbassoc-01bead86902a861c8:
resource "aws_route_table_association" "subnet-0cb7f045d1e65a317__rtbassoc-01bead86902a861c8" {
  route_table_id = aws_route_table.rtb-02fbd8405f5c03c6f.id
  subnet_id      = aws_subnet.subnet-0cb7f045d1e65a317.id
}
