# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-07b8d4e34ea1baed5__rtbassoc-08daeb90195c4ab32:
resource "aws_route_table_association" "subnet-07b8d4e34ea1baed5__rtbassoc-08daeb90195c4ab32" {
  route_table_id = aws_route_table.rtb-0dfa36269beabb19a.id
  subnet_id      = aws_subnet.subnet-07b8d4e34ea1baed5.id
}
