# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-1WZEBQQ9BJQQQ:
resource "aws_iam_role" "r-ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-1WZEBQQ9BJQQQ" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ecs-tasks.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns   = []
  max_session_duration  = 3600
  name                  = "ecsworkshop-crystal-TaskDefTaskRole1EDB4A67-1WZEBQQ9BJQQQ"
  path                  = "/"
  tags                  = {}
  tags_all              = {}

  inline_policy {
    name = "TaskDefTaskRoleDefaultPolicyA592CB18"
    policy = jsonencode(
      {
        Statement = [
          {
            Action   = "ec2:DescribeSubnets"
            Effect   = "Allow"
            Resource = "*"
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
