# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.ecsworkshop-crystal-ecsworkshopCrystal62CE0187-gCLpDcPr6kLR:
resource "aws_cloudwatch_log_group" "ecsworkshop-crystal-ecsworkshopCrystal62CE0187-gCLpDcPr6kLR" {
  name              = "ecsworkshop-crystal-ecsworkshopCrystal62CE0187-gCLpDcPr6kLR"
  retention_in_days = 7
  tags              = {}
  tags_all          = {}
}
