# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-ecsworkshop-crystal-TaskDefExecutionRoleB4775C97-Z3Y5CZ12X2M0:
resource "aws_iam_role" "r-ecsworkshop-crystal-TaskDefExecutionRoleB4775C97-Z3Y5CZ12X2M0" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ecs-tasks.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns   = []
  max_session_duration  = 3600
  name                  = "ecsworkshop-crystal-TaskDefExecutionRoleB4775C97-Z3Y5CZ12X2M0"
  path                  = "/"
  tags                  = {}
  tags_all              = {}

  inline_policy {
    name = "TaskDefExecutionRoleDefaultPolicy0DBB737A"
    policy = jsonencode(
      {
        Statement = [
          {
            Action = [
              "logs:CreateLogStream",
              "logs:PutLogEvents",
            ]
            Effect   = "Allow"
            Resource = format("arn:aws:logs:%s:%s:log-group:ecsworkshop-crystal-ecsworkshopCrystal62CE0187-gCLpDcPr6kLR:*", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
